services:
  frontend:
    # build: .
    image: mikkimichaelis/irecovery-zoom-frontend:latest
    tty: true
    working_dir: /home/node/app
    command: ["npm", "run", "server"]
    ports:
      - "127.0.0.1:3001:9090"
    environment:
      - NPM_CONFIG_CACHE=/home/node/.npm
      - PORT=9090
      - PUBLIC_URL=https://alive-zebra-smoothly.ngrok-free.app
      - REACT_APP_PUBLIC_ROOT=https://alive-zebra-smoothly.ngrok-free.app
      - REACT_APP_AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - REACT_APP_AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - REACT_APP_AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
    # volumes:
      # - ./frontend:/home/node/app
      # - /home/node/app/node_modules